2025-02-25 16:37:54,271 INFO    Thread-58 (_run_job):81199 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_setup.py:_flush():67] Configure stats pid to 81199
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1//lwang/.config/wandb/settings
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/settings
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163754-t2akamts/logs/debug.log
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163754-t2akamts/logs/debug-internal.log
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_init.py:init():761] calling init triggers
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 16, 'hidden_size': 256, 'learning_rate': 0.01, 'num_layers': 2}
config: {'_wandb': {}}
2025-02-25 16:37:54,272 INFO    Thread-58 (_run_job):81199 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-25 16:37:54,272 ERROR   Thread-58 (_run_job):81199 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-02-25 16:37:54,279 INFO    Thread-58 (_run_job):81199 [wandb_run.py:_finish():2112] finishing run linfeng-wang/AMP/sd8ufvee
2025-02-25 16:38:04,317 INFO    Thread-59 (_run_job):81199 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 16:38:04,317 INFO    Thread-59 (_run_job):81199 [wandb_setup.py:_flush():67] Configure stats pid to 81199
2025-02-25 16:38:04,318 INFO    Thread-59 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1//lwang/.config/wandb/settings
2025-02-25 16:38:04,318 INFO    Thread-59 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/settings
2025-02-25 16:38:04,318 INFO    Thread-59 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 16:38:04,318 INFO    Thread-59 (_run_job):81199 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163804-apetmr4k/logs/debug.log
2025-02-25 16:38:04,318 INFO    Thread-59 (_run_job):81199 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163804-apetmr4k/logs/debug-internal.log
2025-02-25 16:38:04,318 INFO    Thread-59 (_run_job):81199 [wandb_init.py:init():761] calling init triggers
2025-02-25 16:38:04,318 INFO    Thread-59 (_run_job):81199 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 64, 'hidden_size': 128, 'learning_rate': 0.001, 'num_layers': 1}
config: {'_wandb': {}}
2025-02-25 16:38:04,318 INFO    Thread-59 (_run_job):81199 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-25 16:38:04,319 ERROR   Thread-59 (_run_job):81199 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-02-25 16:38:04,325 INFO    Thread-59 (_run_job):81199 [wandb_run.py:_finish():2112] finishing run linfeng-wang/AMP/sd8ufvee
2025-02-25 16:38:04,784 INFO    Thread-60 (_run_job):81199 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 16:38:04,785 INFO    Thread-60 (_run_job):81199 [wandb_setup.py:_flush():67] Configure stats pid to 81199
2025-02-25 16:38:04,785 INFO    Thread-60 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1//lwang/.config/wandb/settings
2025-02-25 16:38:04,785 INFO    Thread-60 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/settings
2025-02-25 16:38:04,785 INFO    Thread-60 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 16:38:04,785 INFO    Thread-60 (_run_job):81199 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163804-22u9nlml/logs/debug.log
2025-02-25 16:38:04,785 INFO    Thread-60 (_run_job):81199 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163804-22u9nlml/logs/debug-internal.log
2025-02-25 16:38:04,785 INFO    Thread-60 (_run_job):81199 [wandb_init.py:init():761] calling init triggers
2025-02-25 16:38:04,785 INFO    Thread-60 (_run_job):81199 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 64, 'hidden_size': 64, 'learning_rate': 0.1, 'num_layers': 2}
config: {'_wandb': {}}
2025-02-25 16:38:04,786 INFO    Thread-60 (_run_job):81199 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-25 16:38:04,786 ERROR   Thread-60 (_run_job):81199 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-02-25 16:38:04,792 INFO    Thread-60 (_run_job):81199 [wandb_run.py:_finish():2112] finishing run linfeng-wang/AMP/sd8ufvee
2025-02-25 16:38:14,836 INFO    Thread-61 (_run_job):81199 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 16:38:14,836 INFO    Thread-61 (_run_job):81199 [wandb_setup.py:_flush():67] Configure stats pid to 81199
2025-02-25 16:38:14,836 INFO    Thread-61 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1//lwang/.config/wandb/settings
2025-02-25 16:38:14,836 INFO    Thread-61 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/settings
2025-02-25 16:38:14,836 INFO    Thread-61 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 16:38:14,836 INFO    Thread-61 (_run_job):81199 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163814-zyk77xex/logs/debug.log
2025-02-25 16:38:14,836 INFO    Thread-61 (_run_job):81199 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163814-zyk77xex/logs/debug-internal.log
2025-02-25 16:38:14,837 INFO    Thread-61 (_run_job):81199 [wandb_init.py:init():761] calling init triggers
2025-02-25 16:38:14,837 INFO    Thread-61 (_run_job):81199 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 16, 'hidden_size': 256, 'learning_rate': 0.001, 'num_layers': 2}
config: {'_wandb': {}}
2025-02-25 16:38:14,837 INFO    Thread-61 (_run_job):81199 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-25 16:38:14,837 ERROR   Thread-61 (_run_job):81199 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-02-25 16:38:14,843 INFO    Thread-61 (_run_job):81199 [wandb_run.py:_finish():2112] finishing run linfeng-wang/AMP/sd8ufvee
2025-02-25 16:38:15,341 INFO    Thread-62 (_run_job):81199 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 16:38:15,341 INFO    Thread-62 (_run_job):81199 [wandb_setup.py:_flush():67] Configure stats pid to 81199
2025-02-25 16:38:15,341 INFO    Thread-62 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1//lwang/.config/wandb/settings
2025-02-25 16:38:15,341 INFO    Thread-62 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/settings
2025-02-25 16:38:15,342 INFO    Thread-62 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 16:38:15,342 INFO    Thread-62 (_run_job):81199 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163815-yqqy33tc/logs/debug.log
2025-02-25 16:38:15,342 INFO    Thread-62 (_run_job):81199 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163815-yqqy33tc/logs/debug-internal.log
2025-02-25 16:38:15,342 INFO    Thread-62 (_run_job):81199 [wandb_init.py:init():761] calling init triggers
2025-02-25 16:38:15,342 INFO    Thread-62 (_run_job):81199 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 16, 'hidden_size': 128, 'learning_rate': 0.001, 'num_layers': 3}
config: {'_wandb': {}}
2025-02-25 16:38:15,342 INFO    Thread-62 (_run_job):81199 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-25 16:38:15,343 ERROR   Thread-62 (_run_job):81199 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-02-25 16:38:15,349 INFO    Thread-62 (_run_job):81199 [wandb_run.py:_finish():2112] finishing run linfeng-wang/AMP/sd8ufvee
2025-02-25 16:38:25,390 INFO    Thread-63 (_run_job):81199 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 16:38:25,390 INFO    Thread-63 (_run_job):81199 [wandb_setup.py:_flush():67] Configure stats pid to 81199
2025-02-25 16:38:25,390 INFO    Thread-63 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1//lwang/.config/wandb/settings
2025-02-25 16:38:25,390 INFO    Thread-63 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/settings
2025-02-25 16:38:25,390 INFO    Thread-63 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 16:38:25,391 INFO    Thread-63 (_run_job):81199 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163825-qyqw8xb9/logs/debug.log
2025-02-25 16:38:25,391 INFO    Thread-63 (_run_job):81199 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163825-qyqw8xb9/logs/debug-internal.log
2025-02-25 16:38:25,391 INFO    Thread-63 (_run_job):81199 [wandb_init.py:init():761] calling init triggers
2025-02-25 16:38:25,391 INFO    Thread-63 (_run_job):81199 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 64, 'hidden_size': 128, 'learning_rate': 0.01, 'num_layers': 3}
config: {'_wandb': {}}
2025-02-25 16:38:25,391 INFO    Thread-63 (_run_job):81199 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-25 16:38:25,392 ERROR   Thread-63 (_run_job):81199 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-02-25 16:38:25,397 INFO    Thread-63 (_run_job):81199 [wandb_run.py:_finish():2112] finishing run linfeng-wang/AMP/sd8ufvee
2025-02-25 16:38:25,491 INFO    MainThread:81199 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-25 16:38:25,491 INFO    MainThread:81199 [wandb_init.py:_pause_backend():564] pausing backend
2025-02-25 16:38:37,424 INFO    MainThread:81199 [wandb_init.py:_resume_backend():569] resuming backend
2025-02-25 16:38:37,519 INFO    MainThread:81199 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163837-qyqw8xb9/logs/debug.log
2025-02-25 16:38:37,520 INFO    MainThread:81199 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163837-qyqw8xb9/logs/debug-internal.log
2025-02-25 16:38:37,520 INFO    MainThread:81199 [wandb_init.py:init():761] calling init triggers
2025-02-25 16:38:37,521 INFO    MainThread:81199 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 64, 'hidden_size': 128, 'learning_rate': 0.01, 'num_layers': 3}
config: {'_wandb': {}}
2025-02-25 16:38:37,521 INFO    MainThread:81199 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-25 16:38:37,522 ERROR   MainThread:81199 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-02-25 16:38:38,009 INFO    MainThread:81199 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-25 16:38:38,010 INFO    MainThread:81199 [wandb_init.py:_pause_backend():564] pausing backend
2025-02-25 16:38:38,185 INFO    MainThread:81199 [wandb_init.py:_resume_backend():569] resuming backend
2025-02-25 16:38:38,242 INFO    MainThread:81199 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-25 16:38:38,243 INFO    MainThread:81199 [wandb_init.py:_pause_backend():564] pausing backend
2025-02-25 16:38:43,207 INFO    MainThread:81199 [wandb_init.py:_resume_backend():569] resuming backend
2025-02-25 16:38:43,696 INFO    MainThread:81199 [pyagent.py:run():322] Starting sweep agent: entity=None, project=None, count=20
2025-02-25 16:38:44,115 INFO    Thread-65 (_run_job):81199 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-02-25 16:38:44,115 INFO    Thread-65 (_run_job):81199 [wandb_setup.py:_flush():67] Configure stats pid to 81199
2025-02-25 16:38:44,115 INFO    Thread-65 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1//lwang/.config/wandb/settings
2025-02-25 16:38:44,115 INFO    Thread-65 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/settings
2025-02-25 16:38:44,115 INFO    Thread-65 (_run_job):81199 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-02-25 16:38:44,116 INFO    Thread-65 (_run_job):81199 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163844-q2wqmols/logs/debug.log
2025-02-25 16:38:44,116 INFO    Thread-65 (_run_job):81199 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /mnt/storageG1/lwang/Projects/TB-AMP-design/wandb/run-20250225_163844-q2wqmols/logs/debug-internal.log
2025-02-25 16:38:44,116 INFO    Thread-65 (_run_job):81199 [wandb_init.py:init():761] calling init triggers
2025-02-25 16:38:44,116 INFO    Thread-65 (_run_job):81199 [wandb_init.py:init():766] wandb.init called with sweep_config: {'batch_size': 16, 'hidden_size': 64, 'learning_rate': 0.0001, 'num_layers': 1}
config: {'_wandb': {}}
2025-02-25 16:38:44,116 INFO    Thread-65 (_run_job):81199 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-02-25 16:38:44,117 ERROR   Thread-65 (_run_job):81199 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 779, in init
    with telemetry.context() as tel:
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 749, in _telemetry_callback
    self._telemetry_flush()
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 762, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 70, in _publish_telemetry
    self._publish(rec)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 46, in _publish
    self._sock_client.send_record_publish(record)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 224, in send_record_publish
    self.send_server_request(server_req)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/mnt/storageG1/lwang/miniconda3/envs/new-ml/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-02-25 16:38:44,123 INFO    Thread-65 (_run_job):81199 [wandb_run.py:_finish():2112] finishing run linfeng-wang/AMP/sd8ufvee
2025-02-25 16:38:52,444 INFO    MainThread:81199 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-25 16:38:52,444 INFO    MainThread:81199 [wandb_init.py:_pause_backend():564] pausing backend
2025-02-25 16:39:09,678 INFO    MainThread:81199 [wandb_init.py:_resume_backend():569] resuming backend
2025-02-25 16:39:09,740 INFO    MainThread:81199 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-25 16:39:09,742 INFO    MainThread:81199 [wandb_init.py:_pause_backend():564] pausing backend
2025-02-25 16:39:11,052 INFO    MainThread:81199 [wandb_init.py:_resume_backend():569] resuming backend
2025-02-25 16:39:11,122 INFO    MainThread:81199 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-25 16:39:11,125 INFO    MainThread:81199 [wandb_init.py:_pause_backend():564] pausing backend
2025-02-25 16:39:29,170 INFO    MainThread:81199 [wandb_init.py:_resume_backend():569] resuming backend
2025-02-25 16:39:34,221 INFO    MainThread:81199 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-02-25 16:39:34,221 INFO    MainThread:81199 [wandb_init.py:_pause_backend():564] pausing backend
